name: CICD

on:
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

jobs:
  Build-and-Deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #https://github.com/actions/setup-node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn install --ignore-scripts
          yarn docs:build

      #https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          token: ${{ secrets.TOKEN }}

      #https://github.com/SamKirkland/FTP-Deploy-Action
      - name: Deploy to AliYun FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: qxu1098510115.my3w.com
          username: qxu1098510115
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: docs/.vuepress/dist/
          server-dir: /htdocs/library/
          #dry-run: true